export const fakeItems = [
    {
        id: 1,
        name: 'Item 1',
        image: 'gun1.png',
        price: 100,
        type: 'Rifle',
        skin: 'Asiimov',
        pattern: 500,
        floatValue: 0.025,
        rarity: 'Covert',
        description: 'A beautiful and powerful rifle with an Asiimov skin.',
        itemDuration: '10 hours',
      },
      {
        id: 2,
        name: 'Item 2',
        image: 'gun2.png',
        price: 300,
        type: 'Knife',
        skin: 'Butterfly',
        pattern: 200,
        floatValue: 0.022,
        rarity: 'Rare',
        description: 'A beautiful and powerful knife with an Butterfly skin.',
        itemDuration: '20 hours',
      },
      {
        id: 3,
        name: 'Item 3',
        image: 'gun3.png',
        price: 500,
        type: 'Glove',
        skin: 'Sacred',
        pattern: 12,
        floatValue: 0.262,
        rarity: 'Beautiful',
        description: 'A beautiful and powerful glove with an Sacred skin.',
        itemDuration: '1 hours',
      },
      {
        id: 4,
        name: 'Item 4',
        image: 'gun4.png',
        price: 34,
        type: 'AK',
        skin: 'Dragon',
        pattern: 876,
        floatValue: 0.054,
        rarity: 'NEW',
        description: 'A beautiful and powerful AK with an Dragon skin.',
        itemDuration: '5 hours',
      }
];